/*
 * LUtils
 * Copyright (C) 2026 Luis Staudt
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package net.luis.utils.util;

import org.jspecify.annotations.NonNull;

import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.security.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicLong;

/**
 * Utility class for creating and inspecting {@link UUID UUIDs}.<br>
 * Supports all UUID versions defined by RFC 9562 as well as the well-known constants and namespaces.<br>
 * <p>
 *     The supported versions are:
 * </p>
 * <ul>
 *     <li>{@link #v1() Version 1}: Gregorian time-based, using a random node identifier</li>
 *     <li>{@link #v2(int, int) Version 2}: DCE security, time-based with a local domain and identifier</li>
 *     <li>{@link #v3(UUID, String) Version 3}: Name-based, using MD5</li>
 *     <li>{@link #v4() Version 4}: Random</li>
 *     <li>{@link #v5(UUID, String) Version 5}: Name-based, using SHA-1</li>
 *     <li>{@link #v6() Version 6}: Reordered Gregorian time-based, sortable by creation time</li>
 *     <li>{@link #v7() Version 7}: Unix epoch time-based, sortable by creation time</li>
 *     <li>{@link #v8(long, long) Version 8}: Custom, the given bits are used as-is except for the version and variant bits</li>
 * </ul>
 * All generated UUIDs carry the RFC 9562 variant bits.<br>
 * The time-based versions are monotonic, two UUIDs generated by the same process never share the same timestamp.<br>
 *
 * @see UUID
 *
 * @author Luis-St
 */
public final class UUIDs {
	
	/**
	 * The number of 100-nanosecond intervals between the Gregorian epoch (1582-10-15) and the Unix epoch (1970-01-01).<br>
	 */
	private static final long GREGORIAN_OFFSET = 0x01B21DD213814000L;
	/**
	 * The random source used for all random and pseudo-random parts of the generated UUIDs.<br>
	 */
	private static final SecureRandom RANDOM = new SecureRandom();
	/**
	 * The randomly generated node identifier used by the time-based versions.<br>
	 * The multicast bit is set to mark the node as randomly generated instead of a real MAC address.<br>
	 */
	private static final long NODE = (RANDOM.nextLong() & 0x0000_FFFF_FFFF_FFFFL) | 0x0000_0100_0000_0000L;
	/**
	 * The randomly generated clock sequence used by the time-based versions.<br>
	 */
	private static final long CLOCK_SEQUENCE = RANDOM.nextInt(0x4000);
	/**
	 * The last Gregorian timestamp handed out, used to keep the time-based versions monotonic.<br>
	 */
	private static final AtomicLong LAST_GREGORIAN = new AtomicLong(Long.MIN_VALUE);
	/**
	 * The last Unix timestamp and counter handed out, used to keep version 7 monotonic.<br>
	 * The upper 48 bits hold the timestamp in milliseconds, the lower 12 bits the counter within that millisecond.<br>
	 * The initial value must be zero, since the timestamp is compared against the shifted state.<br>
	 */
	private static final AtomicLong LAST_UNIX = new AtomicLong(0L);
	/**
	 * The nil UUID, all bits are set to zero.<br>
	 */
	public static final UUID NIL = new UUID(0L, 0L);
	/**
	 * The max UUID, all bits are set to one.<br>
	 */
	public static final UUID MAX = new UUID(-1L, -1L);
	/**
	 * The namespace for fully-qualified domain names, used by the name-based versions.<br>
	 */
	public static final UUID NAMESPACE_DNS = UUID.fromString("6ba7b810-9dad-11d1-80b4-00c04fd430c8");
	/**
	 * The namespace for URLs, used by the name-based versions.<br>
	 */
	public static final UUID NAMESPACE_URL = UUID.fromString("6ba7b811-9dad-11d1-80b4-00c04fd430c8");
	/**
	 * The namespace for ISO OIDs, used by the name-based versions.<br>
	 */
	public static final UUID NAMESPACE_OID = UUID.fromString("6ba7b812-9dad-11d1-80b4-00c04fd430c8");
	/**
	 * The namespace for X.500 distinguished names, used by the name-based versions.<br>
	 */
	public static final UUID NAMESPACE_X500 = UUID.fromString("6ba7b814-9dad-11d1-80b4-00c04fd430c8");
	/**
	 * A comparator which compares UUIDs as unsigned 128-bit numbers.<br>
	 * This matches the lexicographical order of the string representation, unlike {@link UUID#compareTo(UUID)} which compares the bits as signed longs.<br>
	 * The comparator does not permit null values.<br>
	 */
	public static final @NonNull Comparator<UUID> UNSIGNED = (first, second) -> {
		Objects.requireNonNull(first, "First uuid must not be null");
		Objects.requireNonNull(second, "Second uuid must not be null");
		
		int result = Long.compareUnsigned(first.getMostSignificantBits(), second.getMostSignificantBits());
		return result != 0 ? result : Long.compareUnsigned(first.getLeastSignificantBits(), second.getLeastSignificantBits());
	};
	/**
	 * A comparator which compares UUIDs by their creation time and falls back to {@link #UNSIGNED} for equal timestamps.<br>
	 * Only UUIDs of version 1, 2, 6 and 7 can be compared, all other versions carry no timestamp.<br>
	 * The comparator does not permit null values.<br>
	 */
	public static final @NonNull Comparator<UUID> TIME_ORDERED = Comparator.comparingLong(UUIDs::unixMillis).thenComparing(UNSIGNED);
	
	/**
	 * Private constructor to prevent instantiation.<br>
	 * This is a static helper class.<br>
	 */
	private UUIDs() {}
	
	/**
	 * Creates a new version 1 UUID.<br>
	 * The UUID is based on the current Gregorian timestamp, a random clock sequence and a random node identifier.<br>
	 * The node identifier and clock sequence are generated once per process, the timestamp is strictly increasing.<br>
	 *
	 * @return The created UUID
	 */
	public static @NonNull UUID v1() {
		long timestamp = nextGregorianTimestamp();
		long msb = ((timestamp & 0xFFFF_FFFFL) << 32) | (((timestamp >>> 32) & 0xFFFFL) << 16) | ((timestamp >>> 48) & 0x0FFFL);
		long lsb = (CLOCK_SEQUENCE << 48) | NODE;
		return assemble(msb, lsb, 1);
	}
	
	/**
	 * Creates a new version 2 DCE security UUID.<br>
	 * The local identifier replaces the low field of the timestamp, the local domain replaces the low byte of the clock sequence.<br>
	 * The local identifier is used as an unsigned 32-bit value, the local domain must fit into a single unsigned byte.<br>
	 * <p>
	 *     The commonly used local domains are:
	 * </p>
	 * <ul>
	 *     <li>{@code 0} - The person domain, the local identifier is a user id</li>
	 *     <li>{@code 1} - The group domain, the local identifier is a group id</li>
	 *     <li>{@code 2} - The organization domain, the local identifier is site-defined</li>
	 * </ul>
	 * Due to the reduced timestamp resolution, version 2 UUIDs should only be used if the DCE security format is required.<br>
	 *
	 * @param localDomain The local domain the identifier belongs to
	 * @param localIdentifier The identifier within the local domain
	 * @return The created UUID
	 * @throws IllegalArgumentException If the local domain is not in the range 0 to 255
	 */
	public static @NonNull UUID v2(int localDomain, int localIdentifier) {
		if (localDomain < 0 || localDomain > 0xFF) {
			throw new IllegalArgumentException("Local domain must be in range 0-255, got " + localDomain);
		}
		
		long timestamp = nextGregorianTimestamp();
		long msb = ((localIdentifier & 0xFFFF_FFFFL) << 32) | (((timestamp >>> 32) & 0xFFFFL) << 16) | ((timestamp >>> 48) & 0x0FFFL);
		long lsb = (((CLOCK_SEQUENCE >>> 8) & 0x3FL) << 56) | ((localDomain & 0xFFL) << 48) | NODE;
		return assemble(msb, lsb, 2);
	}
	
	/**
	 * Creates a new version 3 UUID for the given namespace and name.<br>
	 * The name is encoded as UTF-8 and hashed together with the namespace using MD5.<br>
	 * The same namespace and name always produce the same UUID.<br>
	 *
	 * @param namespace The namespace the name belongs to
	 * @param name The name to create the UUID for
	 * @return The created UUID
	 * @throws NullPointerException If the namespace or the name is null
	 * @see #NAMESPACE_DNS
	 * @see #NAMESPACE_URL
	 * @see #NAMESPACE_OID
	 * @see #NAMESPACE_X500
	 */
	public static @NonNull UUID v3(@NonNull UUID namespace, @NonNull String name) {
		Objects.requireNonNull(namespace, "Namespace uuid must not be null");
		Objects.requireNonNull(name, "Name must not be null");
		
		return v3(namespace, name.getBytes(StandardCharsets.UTF_8));
	}
	
	/**
	 * Creates a new version 3 UUID for the given namespace and name.<br>
	 * The name is hashed together with the namespace using MD5.<br>
	 * The same namespace and name always produce the same UUID.<br>
	 *
	 * @param namespace The namespace the name belongs to
	 * @param name The name to create the UUID for
	 * @return The created UUID
	 * @throws NullPointerException If the namespace or the name is null
	 */
	public static @NonNull UUID v3(@NonNull UUID namespace, byte @NonNull [] name) {
		return nameBased(namespace, name, "MD5", 3);
	}
	
	/**
	 * Creates a new version 4 UUID.<br>
	 * All bits except the version and variant bits are randomly generated.<br>
	 *
	 * @return The created UUID
	 */
	public static @NonNull UUID v4() {
		byte[] data = new byte[16];
		RANDOM.nextBytes(data);
		ByteBuffer buffer = ByteBuffer.wrap(data);
		return assemble(buffer.getLong(), buffer.getLong(), 4);
	}
	
	/**
	 * Creates a new version 5 UUID for the given namespace and name.<br>
	 * The name is encoded as UTF-8 and hashed together with the namespace using SHA-1.<br>
	 * The same namespace and name always produce the same UUID.<br>
	 * Version 5 should be preferred over {@link #v3(UUID, String) version 3} for new applications.<br>
	 *
	 * @param namespace The namespace the name belongs to
	 * @param name The name to create the UUID for
	 * @return The created UUID
	 * @throws NullPointerException If the namespace or the name is null
	 * @see #NAMESPACE_DNS
	 * @see #NAMESPACE_URL
	 * @see #NAMESPACE_OID
	 * @see #NAMESPACE_X500
	 */
	public static @NonNull UUID v5(@NonNull UUID namespace, @NonNull String name) {
		Objects.requireNonNull(namespace, "Namespace uuid must not be null");
		Objects.requireNonNull(name, "Name must not be null");
		
		return v5(namespace, name.getBytes(StandardCharsets.UTF_8));
	}
	
	/**
	 * Creates a new version 5 UUID for the given namespace and name.<br>
	 * The name is hashed together with the namespace using SHA-1.<br>
	 * The same namespace and name always produce the same UUID.<br>
	 * Version 5 should be preferred over {@link #v3(UUID, byte[]) version 3} for new applications.<br>
	 *
	 * @param namespace The namespace the name belongs to
	 * @param name The name to create the UUID for
	 * @return The created UUID
	 * @throws NullPointerException If the namespace or the name is null
	 */
	public static @NonNull UUID v5(@NonNull UUID namespace, byte @NonNull [] name) {
		return nameBased(namespace, name, "SHA-1", 5);
	}
	
	/**
	 * Creates a new version 6 UUID.<br>
	 * Version 6 uses the same data as {@link #v1() version 1}, but stores the timestamp in big-endian order.<br>
	 * The UUIDs are therefore sortable by creation time using their natural or unsigned order.<br>
	 *
	 * @return The created UUID
	 */
	public static @NonNull UUID v6() {
		long timestamp = nextGregorianTimestamp();
		long msb = ((timestamp >>> 12) << 16) | (timestamp & 0x0FFFL);
		long lsb = (CLOCK_SEQUENCE << 48) | NODE;
		return assemble(msb, lsb, 6);
	}
	
	/**
	 * Creates a new version 7 UUID.<br>
	 * The UUID is based on the current Unix timestamp in milliseconds followed by a 12-bit counter and random bits.<br>
	 * The counter is seeded randomly for every new millisecond and incremented for UUIDs created within the same millisecond, the UUIDs are therefore sortable by creation time.<br>
	 * The seed leaves at least 2048 counter values per millisecond, if they are exhausted the method waits for the clock to advance instead of borrowing from the timestamp.<br>
	 * The timestamp therefore never runs ahead of the system clock.<br>
	 * Version 7 should be preferred for database keys and other sortable identifiers.<br>
	 *
	 * @return The created UUID
	 */
	public static @NonNull UUID v7() {
		while (true) {
			long state = LAST_UNIX.get();
			long millis = System.currentTimeMillis() & 0x0000_FFFF_FFFF_FFFFL;
			
			long next;
			if (millis > (state >>> 12)) {
				next = (millis << 12) | RANDOM.nextInt(0x800);
			} else if ((state & 0x0FFFL) == 0x0FFFL) {
				Thread.onSpinWait();
				continue;
			} else {
				next = state + 1;
			}
			
			if (LAST_UNIX.compareAndSet(state, next)) {
				long msb = ((next >>> 12) << 16) | (next & 0x0FFFL);
				return assemble(msb, RANDOM.nextLong(), 7);
			}
		}
	}
	
	/**
	 * Creates a new version 8 UUID from the given bits.<br>
	 * The bits are used as-is, except for the version and variant bits which are overwritten.<br>
	 * The layout of the remaining bits is application-defined.<br>
	 *
	 * @param mostSignificantBits The most significant bits of the UUID
	 * @param leastSignificantBits The least significant bits of the UUID
	 * @return The created UUID
	 */
	public static @NonNull UUID v8(long mostSignificantBits, long leastSignificantBits) {
		return assemble(mostSignificantBits, leastSignificantBits, 8);
	}
	
	/**
	 * Creates a new version 8 UUID from the given bytes.<br>
	 * The bytes are read in big-endian order and used as-is, except for the version and variant bits which are overwritten.<br>
	 * The layout of the remaining bits is application-defined.<br>
	 *
	 * @param data The 16 bytes to create the UUID from
	 * @return The created UUID
	 * @throws NullPointerException If the data is null
	 * @throws IllegalArgumentException If the data is not exactly 16 bytes long
	 */
	public static @NonNull UUID v8(byte @NonNull [] data) {
		Objects.requireNonNull(data, "Data must not be null");
		if (data.length != 16) {
			throw new IllegalArgumentException("Expected 16 bytes, got " + data.length);
		}
		
		ByteBuffer buffer = ByteBuffer.wrap(data);
		return assemble(buffer.getLong(), buffer.getLong(), 8);
	}
	
	/**
	 * Extracts the creation time of the given UUID as Unix timestamp in milliseconds.<br>
	 * Only the time-based versions 1, 2, 6 and 7 carry a timestamp.<br>
	 * The timestamp of a version 2 UUID is truncated to a resolution of roughly 429 seconds and therefore never later than the
	 * actual creation time, since the low field of the timestamp is replaced by the local identifier and read as zero.<br>
	 *
	 * @param uuid The UUID to extract the timestamp from
	 * @return The creation time in milliseconds since the Unix epoch
	 * @throws NullPointerException If the UUID is null
	 * @throws IllegalArgumentException If the UUID is not a time-based UUID
	 */
	public static long unixMillis(@NonNull UUID uuid) {
		Objects.requireNonNull(uuid, "UUID must not be null");
		long msb = uuid.getMostSignificantBits();
		if (uuid.version() == 7) {
			return msb >>> 16;
		}
		
		long timestamp = switch (uuid.version()) {
			case 1 -> ((msb & 0x0FFFL) << 48) | (((msb >>> 16) & 0xFFFFL) << 32) | ((msb >>> 32) & 0xFFFF_FFFFL);
			case 2 -> ((msb & 0x0FFFL) << 48) | (((msb >>> 16) & 0xFFFFL) << 32);
			case 6 -> ((msb >>> 16) << 12) | (msb & 0x0FFFL);
			default -> throw new IllegalArgumentException("UUID version " + uuid.version() + " carries no timestamp");
		};
		return (timestamp - GREGORIAN_OFFSET) / 10_000L;
	}
	
	/**
	 * Converts the given UUID into its 16 byte big-endian representation.<br>
	 * The most significant bits are written first, followed by the least significant bits.<br>
	 *
	 * @param uuid The UUID to convert
	 * @return The 16 bytes of the UUID
	 * @throws NullPointerException If the UUID is null
	 * @see #fromBytes(byte[])
	 */
	public static byte @NonNull [] toBytes(@NonNull UUID uuid) {
		Objects.requireNonNull(uuid, "UUID must not be null");
		return ByteBuffer.allocate(16).putLong(uuid.getMostSignificantBits()).putLong(uuid.getLeastSignificantBits()).array();
	}
	
	/**
	 * Converts the given 16 byte big-endian representation back into a UUID.<br>
	 * The bytes are used as-is, no version or variant bits are applied.<br>
	 *
	 * @param data The 16 bytes to convert
	 * @return The UUID represented by the given bytes
	 * @throws NullPointerException If the data is null
	 * @throws IllegalArgumentException If the data is not exactly 16 bytes long
	 * @see #toBytes(UUID)
	 */
	public static @NonNull UUID fromBytes(byte @NonNull [] data) {
		Objects.requireNonNull(data, "Data must not be null");
		if (data.length != 16) {
			throw new IllegalArgumentException("Expected 16 bytes, got " + data.length);
		}
		
		ByteBuffer buffer = ByteBuffer.wrap(data);
		return new UUID(buffer.getLong(), buffer.getLong());
	}
	
	/**
	 * Assembles a UUID from the given bits by applying the version and variant bits.<br>
	 * The version is written into the four version bits of the most significant bits, the RFC 9562 variant into the two highest bits of the least significant bits.<br>
	 *
	 * @param msb The most significant bits of the UUID
	 * @param lsb The least significant bits of the UUID
	 * @param version The version to apply
	 * @return The assembled UUID
	 */
	private static @NonNull UUID assemble(long msb, long lsb, int version) {
		msb = (msb & 0xFFFF_FFFF_FFFF_0FFFL) | ((long) version << 12);
		lsb = (lsb & 0x3FFF_FFFF_FFFF_FFFFL) | 0x8000_0000_0000_0000L;
		return new UUID(msb, lsb);
	}
	
	/**
	 * Creates a name-based UUID by hashing the given namespace and name with the given algorithm.<br>
	 * The first 16 bytes of the hash are used as the UUID.<br>
	 *
	 * @param namespace The namespace the name belongs to
	 * @param name The name to create the UUID for
	 * @param algorithm The name of the digest algorithm to use
	 * @param version The version to apply
	 * @return The created UUID
	 * @throws NullPointerException If the namespace, the name or the algorithm is null
	 * @throws IllegalStateException If the algorithm is not available on the current platform
	 */
	private static @NonNull UUID nameBased(@NonNull UUID namespace, byte @NonNull [] name, @NonNull String algorithm, int version) {
		Objects.requireNonNull(namespace, "Namespace uuid must not be null");
		Objects.requireNonNull(name, "Name must not be null");
		Objects.requireNonNull(algorithm, "Algorithm must not be null");
		
		MessageDigest digest;
		try {
			digest = MessageDigest.getInstance(algorithm);
		} catch (NoSuchAlgorithmException e) {
			throw new IllegalStateException(algorithm + " is required by every Java platform", e);
		}
		
		digest.update(toBytes(namespace));
		digest.update(name);
		
		ByteBuffer hash = ByteBuffer.wrap(digest.digest(), 0, 16);
		return assemble(hash.getLong(), hash.getLong(), version);
	}
	
	/**
	 * Returns the next Gregorian timestamp in 100-nanosecond intervals since the Gregorian epoch.<br>
	 * The timestamp is strictly increasing, if the system clock did not advance the previous timestamp is incremented by one.<br>
	 *
	 * @return The next timestamp, truncated to 60 bits
	 */
	private static long nextGregorianTimestamp() {
		long last;
		long next;
		do {
			last = LAST_GREGORIAN.get();
			long now = System.currentTimeMillis() * 10_000L + GREGORIAN_OFFSET;
			next = now > last ? now : last + 1;
		} while (!LAST_GREGORIAN.compareAndSet(last, next));
		
		return next & 0x0FFF_FFFF_FFFF_FFFFL;
	}
}
