/*
 * LUtils
 * Copyright (C) 2026 Luis Staudt
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package net.luis.utils.crypto.util;

import net.luis.utils.annotation.type.Facade;
import net.luis.utils.crypto.exception.UnsupportedAlgorithmException;
import org.jspecify.annotations.NonNull;

import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.util.*;

/**
 * Cryptographically secure randomness.<br>
 * <p>
 *     Every entry point in this package that consumes randomness offers an overload taking an explicit {@link SecureRandom},<br>
 *     so the wire formats can be tested against known answers with a fixed source.<br>
 *     Nothing in this library draws from an unreplaceable static source.
 * </p>
 *
 * @author Luis-St
 */
@Facade
public final class CryptoRandom {
	
	/**
	 * The shared random source used by the overloads that do not take one explicitly.<br>
	 */
	private static final SecureRandom RANDOM = new SecureRandom();
	
	/**
	 * Private constructor to prevent instantiation.<br>
	 * This is a static helper class.<br>
	 */
	private CryptoRandom() {}
	
	/**
	 * Generates the given number of random bytes from the shared source.<br>
	 *
	 * @param length The number of bytes to generate
	 * @return The generated bytes
	 * @throws IllegalArgumentException If the length is negative
	 */
	public static byte @NonNull [] bytes(int length) {
		return bytes(RANDOM, length);
	}
	
	/**
	 * Generates the given number of random bytes from the given source.<br>
	 * This overload exists so the wire formats can be tested against known answers with a fixed source.<br>
	 *
	 * @param random The source to draw from
	 * @param length The number of bytes to generate
	 * @return The generated bytes
	 * @throws NullPointerException If the random source is null
	 * @throws IllegalArgumentException If the length is negative
	 */
	public static byte @NonNull [] bytes(@NonNull SecureRandom random, int length) {
		Objects.requireNonNull(random, "Random must not be null");
		if (length < 0) {
			throw new IllegalArgumentException("Length must not be negative, was " + length);
		}
		
		byte[] result = new byte[length];
		random.nextBytes(result);
		return result;
	}
	
	/**
	 * Generates a 16 byte salt.<br>
	 * @return The generated salt
	 */
	public static byte @NonNull [] salt() {
		return bytes(16);
	}
	
	/**
	 * Generates a random integer in the given range.<br>
	 *
	 * @param origin The inclusive lower bound
	 * @param bound The exclusive upper bound
	 * @return The generated value
	 * @throws IllegalArgumentException If the origin is not less than the bound
	 */
	public static int integer(int origin, int bound) {
		return RANDOM.nextInt(origin, bound);
	}
	
	/**
	 * Generates a random token of the given byte length, encoded as unpadded base64url.<br>
	 * The returned string is longer than the requested byte length, since it is an encoding of it.<br>
	 *
	 * @param byteLength The number of random bytes behind the token
	 * @return The encoded token
	 * @throws IllegalArgumentException If the byte length is negative
	 */
	public static @NonNull String tokenBase64Url(int byteLength) {
		return Base64.getUrlEncoder().withoutPadding().encodeToString(bytes(byteLength));
	}
	
	/**
	 * Generates a random token of the given byte length, encoded as lowercase hex.<br>
	 * The returned string is twice as long as the requested byte length.<br>
	 *
	 * @param byteLength The number of random bytes behind the token
	 * @return The encoded token
	 * @throws IllegalArgumentException If the byte length is negative
	 */
	public static @NonNull String tokenHex(int byteLength) {
		return HexFormat.of().formatHex(bytes(byteLength));
	}
	
	/**
	 * Generates a random password of the given length from the given alphabet.<br>
	 * <p>
	 *     The result is a character array rather than a string, so it can be wiped after use.<br>
	 *     The caller is responsible for wiping it.
	 * </p>
	 *
	 * @param length The number of characters to generate
	 * @param alphabet The characters to draw from
	 * @return The generated password
	 * @throws NullPointerException If the alphabet is null
	 * @throws IllegalArgumentException If the length is negative or the alphabet is empty
	 */
	public static char @NonNull [] password(int length, char @NonNull [] alphabet) {
		Objects.requireNonNull(alphabet, "Alphabet must not be null");
		if (length < 0) {
			throw new IllegalArgumentException("Length must not be negative, was " + length);
		}
		if (alphabet.length == 0) {
			throw new IllegalArgumentException("Alphabet must not be empty");
		}
		
		char[] result = new char[length];
		for (int i = 0; i < length; i++) {
			result[i] = alphabet[RANDOM.nextInt(alphabet.length)];
		}
		return result;
	}
	
	/**
	 * Returns a blocking, reseeding source suitable for long-lived key material.<br>
	 * On Linux this may block on first use while the kernel entropy pool initialises.<br>
	 *
	 * @return The strong random source
	 * @throws UnsupportedAlgorithmException If no strong source is configured for this runtime
	 */
	public static @NonNull SecureRandom strong() {
		try {
			return SecureRandom.getInstanceStrong();
		} catch (NoSuchAlgorithmException e) {
			throw UnsupportedAlgorithmException.forAlgorithm("SecureRandom.strong", e);
		}
	}
	
	/**
	 * Returns the shared random source used by this class.<br>
	 * @return The shared random source
	 */
	public static @NonNull SecureRandom instance() {
		return RANDOM;
	}
}
