/*
 * LUtils
 * Copyright (C) 2026 Luis Staudt
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package net.luis.utils.io.database.audit;

import java.time.Clock;

/**
 * Determines where the audit timestamp values originate from.<br>
 *
 * @author Luis-St
 */
public enum SqlAuditValueSource {
	
	/**
	 * The timestamps are generated by the ORM using the configured {@link Clock clock}.<br>
	 */
	ORM_CLOCK,
	/**
	 * The timestamps are generated by the database itself.<br>
	 */
	DATABASE
}
