name: Compile and test on commit

on: [ push ]

permissions:
  contents: read

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v5.0.0
      - name: 'Set up JDK 21'
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: 'Grant Permission to Gradle'
        run: chmod +x gradlew
      - name: 'Setup Gradle'
        uses: gradle/actions/setup-gradle@v4.4.3
      - name: 'License check with Gradle'
        run: ./gradlew checkLicenses
  compile:
    needs: license-check
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v5.0.0
      - name: 'Set up JDK 21'
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: 'Grant Permission to Gradle'
        run: chmod +x gradlew
      - name: 'Setup Gradle'
        uses: gradle/actions/setup-gradle@v4.4.3
      - name: 'Compile with Gradle'
        run: ./gradlew classes # Use classes instead of build to not make the test task redundant
  test:
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v5.0.0
      - name: 'Set up JDK 21'
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: 'Grant Permission to Gradle'
        run: chmod +x gradlew
      - name: 'Setup Gradle'
        uses: gradle/actions/setup-gradle@v4.4.3
      - name: 'Test with Gradle'
        run: ./gradlew test
